# main menu navigation
menu:
  Index: /
  Tags: /tags
  Archives: /archives

dream: The best preparation for tomorrow is doing your best today.

# Miscelaneous
favicon: /favicon.png
logo: /medias/logo.png
featureimg: /medias/default.jpg

# stylesheets loaded in the <head>
stylesheets:
- /libs/awesome/css/font-awesome.min.css
- /libs/materialize/css/materialize.min.css
- /libs/aos/aos.css
- /libs/animate/animate.min.css
- /libs/lightGallery/css/lightgallery.min.css
- /css/matery.css

# scripts loaded in the end of the body
scripts:
- /libs/materialize/js/materialize.min.js
- /libs/masonry/masonry.pkgd.min.js
- /libs/aos/aos.js
- /js/matery.js
- /js/search.js
- /libs/lightGallery/js/lightgallery-all.min.js